# This uses newer and faster docker based build system
sudo: false

services:
  - mysql

# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # aliased to a recent 5.4.x version
  - '5.6'
  - '7.1'
  - '7.3'

env:
  - WP_PROJECT_TYPE=plugin WP_VERSION=latest WP_MULTISITE=0 WP_TEST_URL=http://localhost:12000 WP_TEST_USER=test WP_TEST_USER_PASS=test

before_script:
  # Install composer packages before trying to activate themes or plugins
  # - composer install

  # Install an older version of PHPUnit as WordPress does not support 8.x yet
  - if [[ "$TRAVIS_PHP_VERSION" == "5.6" ]]; then PHPUNIT_VERSION=5.7.9; else PHPUNIT_VERSION=6.5.9; fi
  - wget https://phar.phpunit.de/phpunit-$PHPUNIT_VERSION.phar -O /tmp/phpunit; chmod +x /tmp/phpunit

  # Install test framework
  - git clone https://github.com/Seravo/wordpress-test-template wp-tests
  - bash wp-tests/bin/install-wp-tests.sh test root '' localhost $WP_VERSION
  - rm -rf /tmp/wordpress-tests-lib/includes/
  - svn co --quiet http://develop.svn.wordpress.org/tags/5.4.2/tests/phpunit/includes/ /tmp/wordpress-tests-lib/includes/

script:
  - /tmp/phpunit
